services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
      args:
        USER_ID: $UID
        GROUP_ID: $GID
    ports:
      - "80:8080"
    environment:
      SSL_MODE: "off"
      AUTORUN_ENABLED: "true"
    volumes:
      - "./:/var/www/html"
      - "./docker/php/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql

networks:
  default:
    driver: bridge
